from datetime import date

today = str(date.today())

atomic_points = [
    # =========================
    # Grammar Points
    # =========================
    {
        "id": "ap_g_001",
        "type": "grammar",
        "name": "Polite requests with 'could' and 'would'",
        "description": "Used to make polite requests in service situations.",
        "examples": ["Could I see the menu?", "Would you bring us some water?"],
        "level": "B1",
        "popularity": 0.95,
        "tags": ["restaurant", "politeness"],
        "related": ["ap_f_001", "ap_f_002"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_g_002",
        "type": "grammar",
        "name": "Using 'some' and 'any' for requests",
        "description": "Used to talk about quantities in questions and requests.",
        "examples": ["Can I have some water?", "Do you have any vegetarian dishes?"],
        "level": "B1",
        "popularity": 0.9,
        "tags": ["food", "quantity"],
        "related": ["ap_v_002"],
        "created_at": today,
        "updated_at": today,
    },
    # =========================
    # Vocabulary Points
    # =========================
    {
        "id": "ap_v_001",
        "type": "vocabulary",
        "name": "menu",
        "description": "A list of food and drinks available in a restaurant.",
        "examples": ["Could I see the menu?", "The menu looks great."],
        "level": "B1",
        "popularity": 0.95,
        "tags": ["restaurant"],
        "related": ["ap_f_002"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_v_002",
        "type": "vocabulary",
        "name": "vegetarian",
        "description": "A person who does not eat meat.",
        "examples": ["I'm vegetarian.", "Do you have vegetarian options?"],
        "level": "B1",
        "popularity": 0.9,
        "tags": ["food", "diet"],
        "related": ["ap_g_002", "ap_f_004"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_v_003",
        "type": "vocabulary",
        "name": "reservation",
        "description": "An arrangement to have a table saved at a restaurant.",
        "examples": ["I have a reservation.", "We made a reservation online."],
        "level": "B1",
        "popularity": 0.88,
        "tags": ["restaurant"],
        "related": ["ap_f_003"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_v_004",
        "type": "vocabulary",
        "name": "starter",
        "description": "A small dish served before the main course.",
        "examples": ["I’ll have soup as a starter.", "What starters do you have?"],
        "level": "B1",
        "popularity": 0.82,
        "tags": ["meal"],
        "related": ["ap_v_005"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_v_005",
        "type": "vocabulary",
        "name": "main course",
        "description": "The main dish of a meal.",
        "examples": [
            "I'll have steak for the main course.",
            "The main course comes with rice.",
        ],
        "level": "B1",
        "popularity": 0.9,
        "tags": ["meal"],
        "related": ["ap_v_004"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_v_006",
        "type": "vocabulary",
        "name": "bill",
        "description": "The total amount to pay for a meal.",
        "examples": ["Could we have the bill?", "The bill is $30."],
        "level": "B1",
        "popularity": 0.93,
        "tags": ["payment"],
        "related": ["ap_f_002"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_v_007",
        "type": "vocabulary",
        "name": "water",
        "description": "A common drink served in restaurants.",
        "examples": ["Can I have some water?", "Still or sparkling water?"],
        "level": "B1",
        "popularity": 0.98,
        "tags": ["drink"],
        "related": ["ap_g_002"],
        "created_at": today,
        "updated_at": today,
    },
    # =========================
    # Fluency Points
    # =========================
    {
        "id": "ap_f_001",
        "type": "fluency",
        "name": "I'd like...",
        "description": "A polite way to order food or drinks.",
        "examples": ["I'd like a burger.", "I'd like some water."],
        "level": "B1",
        "popularity": 0.97,
        "tags": ["speaking"],
        "related": ["ap_g_001"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_f_002",
        "type": "fluency",
        "name": "Could I have...?",
        "description": "A polite way to request something.",
        "examples": ["Could I have the menu?", "Could I have the bill?"],
        "level": "B1",
        "popularity": 0.96,
        "tags": ["politeness"],
        "related": ["ap_g_001"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_f_003",
        "type": "fluency",
        "name": "make a reservation",
        "description": "To book a table at a restaurant.",
        "examples": ["I'd like to make a reservation.", "We made a reservation."],
        "level": "B1",
        "popularity": 0.88,
        "tags": ["restaurant"],
        "related": ["ap_v_003"],
        "created_at": today,
        "updated_at": today,
    },
    {
        "id": "ap_f_004",
        "type": "fluency",
        "name": "Do you have any recommendations?",
        "description": "Used to ask for suggestions from staff.",
        "examples": ["Do you have any recommendations?", "What do you recommend?"],
        "level": "B1",
        "popularity": 0.9,
        "tags": ["interaction"],
        "related": ["ap_v_002"],
        "created_at": today,
        "updated_at": today,
    },
]
